### ISSUE TITLE
Goals and Roadmap

### ISSUE THREAD

**Issue by mwadams** [corvus-dotnet/Corvus.EventStore#109]
# Purpose

Create a VS Code extension to help with editing Corvus.EventStore.DomainModel files.

# Features

## Navigation

These features help with rapid navigation around the document.

```[tasklist]
### Tasks
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/110
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/111
```

## Visualization

These features provide a read-only visualization of the document.

```[tasklist]
### Tasks
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/112
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/113
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/114
```

## Editor assist

These features enhance the editing experience of the document to provide error handling and Intellisense.

```[tasklist]
### Tasks
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/115
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/116
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/117
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/119
```

## Code Generation

These features provide code generation from the document.

```[tasklist]
### Tasks
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/118
```
