### ISSUE TITLE
Hyperlink between references

### ISSUE THREAD

**Issue by mwadams** [corvus-dotnet/Corvus.EventStore#111]
```[tasklist]
### Tasks
- [x] From permitted command in a state to command
- [ ] From target state in a transition to state
- [ ] From event in a transition to event
- [ ] https://github.com/corvus-dotnet/Corvus.EventStore/issues/141
- [x] From created event data schema to referenced JSON
```

Still to enumerate
- references in queries and corrective policies
- references in the other direction - e.g. when a command is selected, show references to that command, or when a state is selected show transitions to that state
